### ISSUE TITLE
Revisión de la memoria.

### ISSUE THREAD

**Issue by jam0101** [jam0101/TFGII-Quiz-Grafos#1]
- Objetivos.
- Conceptos teóricos.
- Técnicas.
- Herramientas.

**Comment by jam0101** [comment]
https://mega.co.nz/#!3IQiFCCa!L5XVuwNk9CF3bDKeOvf9FsKp0wtynmqklvprPe0W458

**Comment by jjrodriguez** [comment]
He puesto algún comentario: https://dl.dropboxusercontent.com/u/974309/memoria_grafos.odt
