### ISSUE TITLE
¿Qué día establecimos la siguiente reunión?

### ISSUE THREAD

**Issue by jam0101** [jam0101/TFGII-Quiz-Grafos#10]
¿Qué día establecimos la siguiente reunión?
Me suena que el miércoles 22 o el miércoles 29, pero en el calendario de google esta vez no me aparece.

**Comment by clopezno** [comment]
Es mejor que no generes Issue para este tipo de información. Añade un milestone para jugar con las fechas.
 
No determinamos fechas  porque denpende de cuando tengamos una primera versión de la implementación de esa pregunta basada en el código de trabajo fin de carrera de ITIG que os dejo Juanjo.
