### ISSUE TITLE
Formato de exportación de múltiples preguntas

### ISSUE THREAD

**Issue by clopezno** [jam0101/TFGII-Quiz-Grafos#11]
Después de obtener el fichero con múltiples preguntas lo intento importar a la plataforma Moodle en formato GIFT/texto  y no puede leer las preguntas.
![errorimportargift](https://cloud.githubusercontent.com/assets/1453744/7450672/e39287c8-f247-11e4-8d25-c027f6443d8d.PNG)

**Comment by clopezno** [comment]
Muy interesante modelar los casos de pruebas con Junit e incluir la automatización del proceso de pruebas en el desarrollo.

**Comment by jam0101** [comment]
He incluído algunos casos de prueba JUnit.

El problema a la hora de importar las preguntas aún no lo he arreglado pero sí lo he detectado: Las preguntas MULTICHOICE sólo se admiten en moodle-xml, por lo que al generarlo como GIFT/texto no las leía correctamente.

**Comment by clopezno** [comment]
A partir de tus comentarios he añadido una nueva incidendencia de mejora  #16. 
Intenta acabar de solucinar esta incidencia y cuando lo tengas haz el commit/push con el nuevo código de test y cerrando la incidencia.
