### ISSUE TITLE
Versión ejecutable

### ISSUE THREAD

**Issue by jjrodriguez** [jam0101/TFGII-Quiz-Grafos#17]
Incluir en el repositorio un jar ejecutable que se corresponda con lo que está en la carpeta src, para poder probar la aplicación sin tener que compilar.

**Comment by clopezno** [comment]
Me parece buena idea pero no incluyas el .jar directamente en un commit. Etiqueta la versión y añade el jar.
Utiliza la funcionalidad de releases de Github para incluir el  binario.

![githubrelease](https://cloud.githubusercontent.com/assets/1453744/7725506/8f891e88-fefb-11e4-9f35-169f45ea866a.PNG)

**Comment by clopezno** [comment]
En la siguiente dirección tienes un video con los resultado de la revisión que he hecho
 http://youtu.be/tgKVED5ANMw

**Comment by jam0101** [comment]
La opción de Importar Semilla aún está pendiente de ser bien implementada, así que aún no funciona correctamente.

Igualmente, la opción de generar el grafo de forma visual aún no está hecha. Sólamente consta la opción en el menú, pero no está implementada esa funcionalidad.

Creo que el problema de que no pudieras importar las preguntas en moodle está en un problema que había al generar más de una pregunta a la vez en formato xml, ya que las etiquetas no cerraban correctamente. Ya debería estar arreglado y funcionar correctamente.
