### ISSUE TITLE
Cambiar la codificación a UTF8

### ISSUE THREAD

**Issue by jam0101** [jam0101/TFGII-Quiz-Grafos#18]
Cambiar el encoding a UTF-8 para permitir la compatibilidad con linux.

**Comment by jam0101** [comment]
Cambié la codificación a UTF-8 y todos los caracteres extraños se sustituyeron por un rombo con una interrogación.
Tengo la duda de si, ahora que está marcado como UTF-8, puedo emplear caraceteres ajenos (tildes y eñes) en los comentarios del código o si esto daría errores al importarlo fuera de windows.

**Comment by jam0101** [comment]
Esto debería estar resuelto, en principio.
¿Podéis probar a importarlo en linux u otros sistemas y decirme si ahora ya funciona correctamente?

**Comment by jjrodriguez** [comment]
Esa comprobación es responsabilidad tuya.
