### ISSUE TITLE
Exportación de preguntas cuando no se ha seleccionado el directorio.

### ISSUE THREAD

**Issue by jjrodriguez** [jam0101/TFGII-Quiz-Grafos#25]
Si no he seleccionado el directorio, ¿se generan las preguntas en algún sitio?

En linux el directorio que sale por defecto al pinchar en "Select directory" es el $HOME, pero antes de seleccionar ahí no aparecen las preguntas.

**Comment by jam0101** [comment]
No, la idea es que sólo se impriman a un archivo xml las preguntas si se ha seleccionado un directorio.

Si no se ha seleccionado ningún directorio, las preguntas simplemente se muestran por pantalla en la ventana de la aplicación. La idea de hacerlo de esta forma es poder trastear con la aplicación sin tener que preocuparse por estar generando archivos innecesarios.

Sólo en el caso de que se haya seleccionado un directorio incorrecto, la aplicación da un mensaje de error avisando, al generar las preguntas.
