### ISSUE TITLE
Diseño de preguntas de recorrido de grafos.

### ISSUE THREAD

**Issue by jam0101** [jam0101/TFGII-Quiz-Grafos#3]
- Recorrido.
  + Profundidad.
  + Anchura.
  + Clasificación topológica.
- Algoritmo de Dijkstra.
- Árboles extendidos.
  + A partir del grafo de Primm.
  + A partir del grafo de Kruskal.

**Comment by clopezno** [comment]
Creo que es mejor  crear una tarea por cada tipo de pregunta.
