### ISSUE TITLE
Visualización de pesos en los arcos.

### ISSUE THREAD

**Issue by jjrodriguez** [jam0101/TFGII-Quiz-Grafos#38]
En la representación gráfica del grafo, si hay bastantes arcos es difícil ver los números.

Una posible solución es que las representaciones, en vez de ser excluyentes, se pudieran activar y desactivar independientemente, de manera que para una pregunta se pudiera mostrar el grafo con varias representaciones. Por ejemplo con la representación gráfica y la matriz.

**Comment by jam0101** [comment]
Al final incorporé la opción de poder seleccionar múltiples representaciones. Parece que funciona sin problemas.

**Comment by jjrodriguez** [comment]
Cuando se generan varias preguntas solo se muestra la representación gráfica de la última. ¿Es intencionado?

Al importarlas cada una tiene su representación gráfica.

**Comment by jam0101** [comment]
No, es un problema que ya había notado. No me parece especialmente prioritario ahora mismo en comparación con otras cosas, ya que la importación sí funciona correctamente, pero intentaré solucionarlo si me da tiempo.

**Comment by jjrodriguez** [comment]
OK, tampoco me parece prioritario
