### ISSUE TITLE
Error en recorrido en profundidad.

### ISSUE THREAD

**Issue by jjrodriguez** [jam0101/TFGII-Quiz-Grafos#40]
Pregunta de Recorrido en Profundidad

Partiendo de A, recorre el grafo en profundidad. En caso de poderse seleccionar más de un nodo,los nodos se deben escoger en orden alfabético.
(semilla: 051020705086589825808604532)

La respuesta correcta es: [A, B, D, E].

  A B C D E F 
A 0 0 0 0 1 1 
B 1 0 0 0 0 0 
C 0 0 1 0 0 1 
D 1 1 1 0 0 0 
E 1 0 0 1 0 0 
F 0 0 1 0 0 0 

A: E, F
B: A
C: C, F
D: A, B, C
E: A, D
F: C

Del nodo A no se puede ir al B. El recorrido debería ser [A, E, D, C, F, B].

**Comment by jam0101** [comment]
El fallo, que es el mismo que se daba en las preguntas de anchura, está arreglado: hallarVecinos() devolvía los arcos entrantes en lugar de los salientes.
