### ISSUE TITLE
Error en recorrido en anchura

### ISSUE THREAD

**Issue by jjrodriguez** [jam0101/TFGII-Quiz-Grafos#41]
Pregunta de Recorrido en Anchura

Partiendo de A, recorre el grafo en anchura. En caso de poderse seleccionar más de un nodo,los nodos se deben escoger en orden alfabético.
(semilla: 151020701490124626219413733)

La respuesta correcta es: [A, C, D, E, F].

  A B C D E F 
A 0 0 0 0 0 1 
B 0 0 0 0 0 0 
C 1 0 0 1 0 1 
D 1 0 1 0 1 0 
E 1 0 0 1 0 0 
F 1 1 0 0 0 0 

A: F
B
C: A, D, F
D: A, C, E
E: A, D
F: A, B

Del nodo A no se puede ir al C. El recorrido en anchura debería ser [A, F, B]

**Comment by jam0101** [comment]
El fallo, que es el mismo que se daba en las preguntas de profundidad, está arreglado: hallarVecinos() devolvía los arcos entrantes en lugar de los salientes.
