### ISSUE TITLE
Error en Dijkstra

### ISSUE THREAD

**Issue by jjrodriguez** [jam0101/TFGII-Quiz-Grafos#42]
Pregunta del Algoritmo de Dijkstra

Calcula la distancia mínima entre el nodo A y cada uno de los otros nodos del grafo.
(semilla: 351040706076775968117608537)

Distancia del nodo A al nodo B: 16.
Distancia del nodo A al nodo C: infinito.
Distancia del nodo A al nodo D: -2147483642.
Distancia del nodo A al nodo E: infinito.
Distancia del nodo A al nodo F: 7.

  A B C D E F 
A 6 0 0 0 0 7 
B 0 0 0 0 0 9 
C 9 4 0 7 0 0 
D 0 5 0 0 0 0 
E 1 8 2 3 7 8 
F 0 9 0 0 0 5 

A: A (6), F (7)
B: F (9)
C: A (9), B (4), D (7)
D: B (5)
E: A (1), B (8), C (2), D (3), E (7), F (8)
F: B (9), F (5)

La distancia de A a D no puede ser  -2147483642.

**Comment by jam0101** [comment]
El fallo está arreglado: Todas las cantidades enormes se muestran ya como infinito. Esto incluye las preguntas en Moodle, donde se estaba pidiendo a los alumnos que introdugeran esas cantidades enormes. Ahora, en lugar de eso se pide poner una 'i' cuando el valor sea infinito.
