### ISSUE TITLE
Pregunta 2 - Recorrido en anchura

### ISSUE THREAD

**Issue by jam0101** [jam0101/TFGII-Quiz-Grafos#5]

**Comment by jjrodriguez** [comment]
Animaciones y ejercicios de la búsqueda en anchura:

http://www.cs.usfca.edu/~galles/visualization/BFS.html

http://www.cse.hut.fi/en/research/SVG/TRAKLA2/exercises/BFS-19.html

**Comment by jam0101** [comment]
Pregunta 1. Recorrido en Anchura
Enunciado
Partiendo de A, recorre el grafo en anchura. Los nodos se deben escoger en orden alfabético.
El resultado de ordenar el grafo es el siguiente: [
{1:MULTICHOICE:%100%A#Correcto~%-100%B#Error~%-100%C#Error~%-100%D#Error} ,
{1:MULTICHOICE:%-100%A#Error~%100%B#Correcto~%-100%C#Error~%-100%D#Error} ,
{1:MULTICHOICE:%-100%A#Error~%-100%B#Error~%-100%C#Error~%100%D#Correcto} ,
{1:MULTICHOICE:%-100%A#Error~%-100%B#Error~%100%C#Correcto~%-100%D#Error} ]

Parámetros
Nº de nodos. Número de nodos que tendrá el grafo.
Porcentaje de arcos. Valor entre el 0 y el 1. Con 0, el grafo tendrá la cantidad mínima imprescindible de arcos para juntar todos los nodos (grafo conexo). A mayor sea el valor, se irán añadiendo arcos de forma aleatoria. Con 1, existirán todos los arcos posibles entre los nodos.
Dirigido o No dirigido. Determina si el grafo será o no dirigido.

Penalización
Dado que un sólo error significará que el recorrido se ha realizado de forma errónea, se penalizará de forma grave cada fallo (Restando el total del valor de la pregunta: %-100%).
De esta forma, se dificultará que el usuario pueda aprobar la pregunta simplemente probando respuestas al azar.

Retroalimentación
Al corregirse una opción, se indicará si fue correcta o no (“Correcto” o bien “Error”).

**Comment by clopezno** [comment]
La retroalimentación a nivel de respuesta "Correcto" o "Error" no aporta información útil para aprender. Esa información la esta dando la propia nota. Si quieres añadir esa retroalimentación deberías añadir algún enlace de consulta a la documentación teoríca del algoritmo sólo en caso de error. Puedes añadir un parámetro msgNegativeFeedback.

Hay otra retroalimentación que no has considerado que es a nivel de pregunta completa. Es en este caso donde puedes generar un informe de ejecución del recorrido paso a paso apoyándote con algún gráfico.

**Comment by clopezno** [comment]
Carga los fuentes del proyecto que te pasamos en GitHub e implementa esta primera versión de  tipo de preguntas primero sin retroalimentación. 
Cuando hagas los cambios haz referencia a esta Issue #5

**Comment by jam0101** [comment]
No sé cómo se hace referencia al commit en una issue, pero acabo de subir el código con el prototipo que genera preguntas de Recorrido Anchura y de Profunidad, como hablamos.

Al final decidí escribir el código desde cero porque no me estaba resultando nada cómodo trabajar con el código de la práctiva anterior.

La interfaz es bastante imperfecta ahora mismo aún, pero creo que para probar el prototipo será más que suficiente.
