### ISSUE TITLE
Pregunta 3 - Clasificación topológica

### ISSUE THREAD

**Issue by jam0101** [jam0101/TFGII-Quiz-Grafos#6]

**Comment by jam0101** [comment]
Se da el problema de que, al generar al azar los grafos, muchas veces existen demasiados arcos como para realizar una clasificación topológica, ya que no existe ningún nodo que no tenga ningún nodo de entrada.
De momento he resuelto este problema limitando los valores que se pueden introducir en "Porcentaje de Arcos" a valores pequeños (5% o menos de probabilidad de crear cada arco). Así no existen demiasados arcos y generalmente se crean preguntas realizables.

**Comment by jjrodriguez** [comment]
Lo que habría que hacer es generar grafos sin ciclos.

Por ejemplo: ordenas los nodos aleatoriamente y solo añades arcos que vayan de un nodo anterior  (según ese orden) a un nodo posterior.

**Comment by jjrodriguez** [comment]
En la barra de desplazamiento para el porcentaje de arcos no sale el valor máximo. 

En el texto de ayuda se dice que 100% para que sea completamente conexo, pero si es dirigido y completamente conexo tendría ciclos y  no sería posible la clasificación tipológica.
